/** @format */

export const COFFEE_LIST_REQUEST = 'COFFEE_LIST_REQUEST';
export const COFFEE_LIST_SUCCESS = 'COFFEE_LIST_SUCCESS';
export const COFFEE_LIST_FAIL = 'COFFEE_LIST_FAIL';

export const COFFEE_DETAILS_REQUEST = 'COFFEE_DETAILS_REQUEST';
export const COFFEE_DETAILS_SUCCESS = 'COFFEE_DETAILS_SUCCESS';
export const COFFEE_DETAILS_FAIL = 'COFFEE_DETAILS_FAIL';

export const EQUIPMENT_LIST_REQUEST = 'EQUIPMENT_LIST_REQUEST';
export const EQUIPMENT_LIST_SUCCESS = 'EQUIPMENT_LIST_SUCCESS';
export const EQUIPMENT_LIST_FAIL = 'EQUIPMENT_LIST_FAIL';

export const EQUIPMENT_DETAILS_REQUEST = 'EQUIPMENT_DETAILS_REQUEST';
export const EQUIPMENT_DETAILS_SUCCESS = 'EQUIPMENT_DETAILS_SUCCESS';
export const EQUIPMENT_DETAILS_FAIL = 'EQUIPMENT_DETAILS_FAIL';
